config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users

  namespace :admin do
    root "static_pages#index"
    resources :categories, except: :show
    resources :authors, except: :show
    resources :publishers, except: :show
    resources :users, except: :show
    resources :books
    resources :requests, only: %i(index update)
  end

  resources :users, only: :show
  resources :books, only: %i(index show)
  resources :requests, only: :create
  resources :likes, only: %i(create destroy)
  resources :comments, only: %i(create destroy)
  resources :ratings, only: :create
  resources :authors, only: :show
  resources :publishers, only: :show
  resources :categories, only: :show
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_books
  has_many :books, through: :author_books
  has_many :follows, dependent: :destroy

  validates :name, presence: true, uniqueness: {case_sensitive: false},
    length: {maximum: Settings.models.author.max_name}
  validates :phone, presence: true,
    length: {maximum: Settings.models.author.max_phone}
  validates :address, presence: true

  scope :alphabet, ->{order name: :asc}
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < AdminController
  before_action :load_author, only: %i(edit update destroy)

  def index
    @authors = Author.alphabet.paginate page: params[:page],
      per_page: Settings.per_page.authors
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new author_params
    if @author.save
      flash[:success] = t "controller.author.create.success"
      redirect_to admin_authors_path
    else
      flash[:danger] = t "controller.author.create.failed"
      render :new
    end
  end

  def edit; end

  def update
    if @author.update_attributes author_params
      flash[:success] = t "controller.author.update.success"
      redirect_to admin_authors_path
    else
      render :edit
    end
  end

  def destroy
    if @author.destroy
      flash[:success] = t "controller.author.destroy.success"
    else
      flash[:danger] = t "controller.author.destroy.failed"
    end
    redirect_to admin_authors_path
  end

  private

  def author_params
    params.require(:author).permit :name, :phone, :address
  end

  def load_author
    @author = Author.find_by id: params[:id]
    return if @author
    flash[:danger] = t "controller.author.load_fail"
    redirect_to admin_authors_path
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find_by id: params[:id]
    return if @author
    flash[:danger] = t "controller.author.load_fail"
    redirect_to books_path
  end
end

app/views/admin/authors/_author.html.erb
<tr>
  <td align="center">
    <%= link_to edit_admin_author_path(author), class: "btn btn-default" do %>
      <em class="fa fa-pencil"></em>
    <% end %>
    <%= link_to admin_author_path(author), method: :delete, class: "btn btn-danger",
      data: {confirm: t("admin.authors.you_sure")} do %>
      <em class="fa fa-trash"></em>
    <% end %>
  </td>
  <td><%= author.name %></td>
  <td><%= author.phone %></td>
  <td><%= author.address %></td>
</tr>

app/views/admin/authors/_form.html.erb
<%= form_for [:admin, @author] do |f| %>
  <%= render "shared/error_messages", object: @author%>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :phone %>
  <%= f.text_field :phone, class: "form-control" %>
  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control" %>
  <br>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/authors/edit.html.erb
<% provide :title, t("admin.authors.edit") %>
<% provide :button_text, t("admin.authors.update") %>
<%= render "admin/static_pages/layout" %>
  <content class="col-md-6 content">
    <h2><%= t "admin.authors.update" %></h2>
    <div class="row">
      <div class="col-md-12">
        <%= render "form" %>
      </div>
    </div>
  </content>
</div>

app/views/admin/authors/index.html.erb
<% provide :title, t("admin.authors.author") %>
<%= render "admin/static_pages/layout" %>
  <content class="col-md-6 content">
    <div class="col-md-11">
      <%= render "shared/flash" %>
      <div class="panel panel-default panel-table">
        <div class="panel-heading">
          <div class="row">
            <div class="col col-xs-6">
              <h3 class="panel-title"><%= t "author" %></h3>
            </div>
            <div class="col col-xs-6 text-right">
                <%= link_to new_admin_author_path do %>
                  <button type="button" class="btn btn-sm btn-primary btn-create">
                    <%= t "admin.create" %>
                  </button>
                <% end %>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <table class="table table-striped table-bordered table-list">
            <thead>
              <tr>
                <th><em class="fa fa-cog"></em></th>
                <th><%= t "name" %></th>
                <th><%= t "phone" %></th>
                <th><%= t "address" %></th>
              </tr>
            </thead>
            <tbody>
              <% @authors.each do |author| %>
                <tr>
                  <td align="center">
                    <%= link_to edit_admin_author_path(author), class: "btn btn-default" do %>
                      <em class="fa fa-pencil"></em>
                    <% end %>
                    <%= link_to admin_author_path(author), method: :delete, class: "btn btn-danger",
                      data: {confirm: t("admin.authors.you_sure")} do %>
                      <em class="fa fa-trash"></em>
                    <% end %>
                  </td>
                  <td><%= author.name %></td>
                  <td><%= author.phone %></td>
                  <td><%= author.address %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <%= will_paginate %>
    </div>
  </content>
</div>

app/views/admin/authors/new.html.erb
<% provide :title, t("admin.authors.new") %>
<% provide :button_text, t("admin.authors.create") %>
<%= render "admin/static_pages/layout" %>
  <content class="col-md-6 content">
    <h2><%= t "admin.authors.create" %></h2>
    <div class="row">
      <div class="col-md-12">
        <%= render "form" %>
      </div>
    </div>
</content>
</div>