config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users

  namespace :admin do
    root "static_pages#index"
    resources :categories, except: :show
    resources :authors, except: :show
    resources :publishers, except: :show
    resources :users, except: :show
    resources :books
    resources :requests, only: %i(index update)
  end

  resources :users, only: :show
  resources :books, only: %i(index show)
  resources :requests, only: :create
  resources :likes, only: %i(create destroy)
  resources :comments, only: %i(create destroy)
  resources :ratings, only: :create
  resources :authors, only: :show
  resources :publishers, only: :show
  resources :categories, only: :show
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true, uniqueness: {case_sensitive: false},
    length: {maximum: Settings.models.publisher.max_name}
  validates :phone, presence: true,
    length: {maximum: Settings.models.publisher.max_phone}
  validates :address, presence: true

  scope :alphabet, ->{order name: :asc}
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < AdminController
  before_action :load_publisher, only: %i(edit update destroy)

  def index
    @publishers = Publisher.alphabet.paginate page: params[:page],
      per_page: Settings.per_page.publishers
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new publisher_params
    if @publisher.save
      flash[:success] = t "controller.publisher.create.success"
      redirect_to admin_publishers_path
    else
      flash[:danger] = t "controller.publisher.create.failed"
      render :new
    end
  end

  def edit; end

  def update
    if @publisher.update_attributes publisher_params
      flash[:success] = t "controller.publisher.update.success"
      redirect_to admin_publishers_path
    else
      render :edit
    end
  end

  def destroy
    if @publisher.destroy
      flash[:success] = t "controller.publisher.destroy.success"
    else
      flash[:danger] = t "controller.publisher.destroy.failed"
    end
    redirect_to admin_publishers_path
  end

  private

  def publisher_params
    params.require(:publisher).permit :name, :phone, :address
  end

  def load_publisher
    @publisher = Publisher.find_by id: params[:id]
    return if @publisher
    flash[:danger] = t "controller.publisher.load_fail"
    redirect_to admin_publishers_path
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def show
    @publisher = Publisher.find_by id: params[:id]
    return if @publisher
    flash[:danger] = t "controller.publisher.load_fail"
    redirect_to books_path
  end
end

app/views/admin/publishers/_form.html.erb
<%= form_for [:admin, @publisher] do |f| %>
  <%= render "shared/error_messages", object: @publisher%>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :phone %>
  <%= f.text_field :phone, class: "form-control" %>
  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control" %>
  <br>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/publishers/_publisher.html.erb
<tr>
  <td align="center">
    <%= link_to edit_admin_publisher_path(publisher), class: "btn btn-default" do %>
      <em class="fa fa-pencil"></em>
    <% end %>
    <%= link_to admin_publisher_path(publisher), method: :delete,
      class: "btn btn-danger", data: {confirm: t("admin.publishers.you_sure")} do %>
      <em class="fa fa-trash"></em>
    <% end %>
  </td>
  <td><%= publisher.name %></td>
  <td><%= publisher.phone %></td>
  <td><%= publisher.address %></td>
</tr>

app/views/admin/publishers/edit.html.erb
<% provide :title, t("admin.publishers.edit") %>
<% provide :button_text, t("admin.publishers.update") %>
<%= render "admin/static_pages/layout" %>
  <content class="col-md-6 content">
    <h2><%= t "admin.publishers.update" %></h2>
    <div class="row">
      <div class="col-md-12">
        <%= render "form" %>
      </div>
    </div>
  </content>
</div>

app/views/admin/publishers/index.html.erb
<% provide :title, t("admin.publishers.publisher") %>
<%= render "admin/static_pages/layout" %>
  <content class="col-md-9 content">
    <div class="col-md-11">
      <%= render "shared/flash" %>
      <div class="panel panel-default panel-table">
        <div class="panel-heading">
          <div class="row">
            <div class="col col-xs-6">
              <h3 class="panel-title"><%= t "publisher" %></h3>
            </div>
            <div class="col col-xs-6 text-right">
                <%= link_to new_admin_publisher_path do %>
                  <button type="button" class="btn btn-sm btn-primary btn-create">
                    <%= t "admin.create" %>
                  </button>
                <% end %>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <table class="table table-striped table-bordered table-list">
            <thead>
              <tr>
                <th><em class="fa fa-cog"></em></th>
                <th><%= t "name" %></th>
                <th><%= t "phone" %></th>
                <th><%= t "address" %></th>
              </tr>
            </thead>
            <tbody>
              <%= render @publishers %>
            </tbody>
          </table>
        </div>
      </div>
      <%= will_paginate %>
    </div>
  </content>
</div>

app/views/admin/publishers/new.html.erb
<% provide :title, t("admin.publishers.new") %>
<% provide :button_text, t("admin.publishers.create") %>
<%= render "admin/static_pages/layout" %>
  <content class="col-md-6 content">
    <h2><%= t "admin.publishers.create" %></h2>
    <div class="row">
      <div class="col-md-12">
        <%= render "form" %>
      </div>
    </div>
  </content>
</div>